### ISSUE TITLE
By default in filter dropdown yes/no is displaying with result

### ISSUE THREAD

**Issue by anson2590** [holyketzer/activeadmin-ajax_filter#29] opened 2018-06-07 09:15 UTC
I am using activeadmin-ajax_filter to filter within activeadmin, In filter drop down i am able to filter values everything is working fine but when i click the dropdown by default yes and no option is coming by default with other result can you please help me fix this issue.

code:
ActiveAdmin.register Customer do
include ActiveAdmin::AjaxFilter
end

ActiveAdmin.register User do
filter :customer_id,
         as: :ajax_select,
         label: 'Customers',
         data: {
           search_fields: [:name],
           url: :filter_admin_customer_path,
           ajax_search_fields: [:name],
           ordering: []
         }
end

Above is my code for filter, dropdown search filtering everything is working fine, but on dropdown by default yes and no option is also coming which i dont wont it to happen. Please help me to solve this issue.

**Comment by ParthChugh** [comment] 2018-10-10 15:57
Did you figure this out?

**Comment by anson2590** [comment] 2018-10-11 13:34
Nop still im facing this issue

**Comment by anson2590** [comment] 2018-10-11 13:34
Nope, Still i am facing this issue.

**Comment by holyketzer** [comment] 2018-12-04 15:18
Can't reproduce it. Could you share screenshot and source code

**Comment by holyketzer** [comment] 2019-02-23 16:16
I got it. It comes from deepness of Formtastic, and it happens when it can't infer the initial collection set, like here:

```ruby
filter :pod_project_id, as: :ajax_select, data: {
  search_fields: [:name],
  url: :filter_admin_projects_path
}
```
<img width="187" alt="screenshot 2019-02-23 at 19 09 51" src="https://user-images.githubusercontent.com/987021/53288900-8b6cc580-379f-11e9-9e18-afbf4232503b.png">


It can be fixed by explicitly setting the initial collection:
```ruby
filter :pod_project_id, as: :ajax_select, collection: -> { Project.limit(5) }, data: {
  search_fields: [:name],
  url: :filter_admin_projects_path
}
```

**Closed by holyketzer** 2019-02-23 16:16 UTC
